# Generated by Django 4.2.7 on 2023-11-09 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_chat', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGptBotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageInput', models.TextField()),
                ('bot_image', models.ImageField(upload_to='users_image_ai')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
